server:
  port: 8081

eureka:
  instance:
    hostname: locahost
  client:
    # 유레카 서버에 본인 서비스를 등록할 건지 여부
    register-with-eureka: false
    # 유레카 서버로부터 서비스 목록을 로컬 캐시에 저장할 건지 여부, 둘 다 기본값 true라서 지정하지 않아도 상관 없다.
    fetch-registry: false



